image: blockstream/gdk_rpc@sha256:e0ca2d21faa0cc1a932d8b4d771da7118f73346391cbb2cd797ea14d16e08aff

variables:
  GDK_LOCATION: "/gdk"
  GDK_TARGET: "build-clang"

test_gdk_rpc_rust_c:
  script:
    - cd $CI_PROJECT_DIR
    - ./build_deps.sh
    - source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all --release && ./test.sh

test_gdk_rpc_rust_c_ndk_armv7:
  script:
    - cd $CI_PROJECT_DIR
    - ./ndk.sh armeabi-v7a

test_gdk_rpc_rust_c_ndk_arm64:
  script:
    - cd $CI_PROJECT_DIR
    - ./ndk.sh arm64-v8a

test_gdk_rpc_rust_c_ndk_x86_64:
  script:
    - cd $CI_PROJECT_DIR
    - ./ndk.sh x86_64

test_gdk_rpc_rust_c_ndk_x86:
  script:
    - cd $CI_PROJECT_DIR
    - ./ndk.sh x86
