image: blockstream/gdk_rpc@sha256:f9f1bc6f5d512553e4c3cd327fe74afb7707353d0a119d6a385c1d8d1ba1c23a

test_gdk_rpc_rust_c:
  script:
    - cd $CI_PROJECT_DIR
    - source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all --release && ./test.sh

test_gdk_rpc_rust_c_ndk:
  script:
    - cd $CI_PROJECT_DIR
    - ./ndk.sh
