image: blockstream/gdk_rpc@sha256:e0ca2d21faa0cc1a932d8b4d771da7118f73346391cbb2cd797ea14d16e08aff

test_gdk_rpc_rust_c:
  script:
    - cd $CI_PROJECT_DIR
    - source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all --release && ./test.sh

test_gdk_rpc_rust_c_ndk:
  script:
    - cd $CI_PROJECT_DIR
    - ./ndk.sh
