image: blockstream/gdk_rpc@sha256:97af03d2130e8971e4b8658bce40549e261d33260f750a594f1773699f5521bb

test_gdk_rpc_no_liquid:
  script:
    - cd $CI_PROJECT_DIR
    - source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --no-default-features --all --release

test_gdk_rpc_rust_c:
  script:
    - cd $CI_PROJECT_DIR
    - source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all --release
