language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=blockstream/gdk_rpc
    - DOCKERHASH=6b21a147e8099d78a9c368bdb297d979f9f93a209bc89b82ce27719c54f1a224
  matrix:
    - UNUSED=true


script:
  - docker run -v $PWD:/gdk_rpc $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk_rpc && source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all && ./test.sh"
