language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=blockstream/gdk_rpc
    - DOCKERHASH=d02d9a6999ac8f9e05b12d2dcf8d3fd0ee5d1c5dfcb5c70efd1f6eaf48a075d5
  matrix:
    - UNUSED=true


script:
  - docker run -v $PWD:/gdk_rpc $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk_rpc && source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all && cargo test --all && ./test.sh"
