language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=blockstream/gdk_rpc
    - DOCKERHASH=97af03d2130e8971e4b8658bce40549e261d33260f750a594f1773699f5521bb
  matrix:
    - UNUSED=true

matrix:
  include:
    - name: fmt checks and release build
      script:
        - docker run -v $PWD:/gdk_rpc $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk_rpc && source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --all --release"
    - name: fmt checks and release build non default
      script:
        - docker run -v $PWD:/gdk_rpc $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk_rpc && source /root/.cargo/env && cargo fmt --all -- --check && cargo check --all && cargo clippy --all && cargo build --no-default-features --all --release"
