[package]
name = "gdk-rpc"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
license = "(MIT)"
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
bitcoincore-rpc = "0.2"
jsonrpc = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
libc = "0.2"
lazy_static = "1.3"
bip39 = "0.6.0-beta"
bitcoin = "0.17"

[dependencies.secp256k1]
version = "0.12"
features = [ "rand" ]
